# Generated by Django 6.0.5 on 2026-05-22 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_deleted_at_alter_user_avatar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_users",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кто удалил",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="restored_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата восстановления"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="restored_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="restored_users",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кто восстановил",
            ),
        ),
    ]
