# Generated by Django 6.0.5 on 2026-05-17 13:41

from django.db import migrations, models

import documents.models
import documents.validators


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="user_note",
            field=models.TextField(
                blank=True,
                help_text="Пояснение к документу (для модератора)",
                verbose_name="Комментарий владельца",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                upload_to=documents.models.user_document_path,
                validators=[documents.validators.check_document_file],
                verbose_name="Файл",
            ),
        ),
    ]
