# Generated by Django 6.0.5 on 2026-05-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_documentlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="comment",
            field=models.TextField(
                help_text="Причина отклонения (заполняется администратором)",
                verbose_name="Комментарий",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Черновик"),
                    ("pending", "На рассмотрении"),
                    ("approved", "Подтверждён"),
                    ("rejected", "Отклонён"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
