# Generated by Django 6.0.5 on 2026-05-19 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_alter_document_comment_alter_document_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Заполняется администратором при отклонении",
                verbose_name="Причина отклонения",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="user_note",
            field=models.TextField(
                help_text="Пояснение к документу",
                verbose_name="Комментарий пользователя",
            ),
        ),
    ]
