# Generated by Django 6.0.5 on 2026-05-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0005_alter_document_comment_alter_document_user_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("created", "Создан"),
                    ("submitted", "Отправлен на проверку"),
                    ("approved", "Подтверждён"),
                    ("rejected", "Отклонён"),
                    ("file_updated", "Файл заменён"),
                    ("deleted", "Удалён"),
                ],
                max_length=20,
            ),
        ),
    ]
