"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Локально читаем .env, в Docker переменные уже загружены через env_file
if not os.path.exists("/.dockerenv"):
    load_dotenv(".env", override=True)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Приложения
    'users',
    'documents',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),  # Имя нашей базы
        "USER": os.getenv("DB_USER"),  # Имя пользователя PostgreSQL
        "PASSWORD": os.getenv("DB_PASSWORD"),  # Пароль пользователя PostgreSQL
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
        # Нельзя использовать логин/email как часть пароля
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        # Минимальная длина пароля (по умолчанию 8 символов)
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
        # Запрещает популярные пароли (qwerty, 123456, password)
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
        # Запрещает пароли, состоящие только из цифр (12345678)
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

# Язык интерфейса (кнопки, надписи в админке)
LANGUAGE_CODE = "en-us"

# Часовой пояс
TIME_ZONE = 'UTC'

# Интернационализация (переводы на другие языки)
USE_I18N = True

# Использовать часовые пояса (хранить время в UTC, показывать в локальном)
USE_TZ = True


# ============================================
# СТАТИЧЕСКИЕ И МЕДИА ФАЙЛЫ
# ============================================

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# URL для доступа к статике (CSS, JS, картинки сайта)
STATIC_URL = "static/"

# Где искать статические файлы
if DEBUG:
    # Разработка: ищем здесь
    STATICFILES_DIRS = [BASE_DIR / "static"]
else:
    # Папка, куда collectstatic собирает ВСЮ статику для продакшена
    # После деплоя запустить: python manage.py collectstatic
    # Продакшен: собираем сюда
    STATIC_ROOT = BASE_DIR / "staticfiles"

# URL для доступа к медиа-файлам (загруженные пользователем файлы)
MEDIA_URL = "media/"

# Папка, где хранятся загруженные пользователями файлы
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# ТИП ПОЛЯ ПО УМОЛЧАНИЮ ДЛЯ ПЕРВИЧНЫХ КЛЮЧЕЙ
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ============================================
# КАСТОМНАЯ МОДЕЛЬ ПОЛЬЗОВАТЕЛЯ
# ============================================

# Вместо стандартной модели User используется своя (users.User)
# Позволяет добавить свои поля (телефон, аватар, дата рождения)
AUTH_USER_MODEL = "users.User"
