"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from celery.schedules import crontab
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Загружаем .env только если мы НЕ в Docker
if not os.path.exists("/.dockerenv"):
    env_path = os.path.join(BASE_DIR, ".env")
    if os.path.exists(env_path):
        load_dotenv(env_path, override=True)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG")

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    # Стандартные приложения Django
    "django.contrib.admin",  # Админ-панель (yourdomain.ru/admin/)
    "django.contrib.auth",  # Пользователи, группы, права доступа
    "django.contrib.contenttypes",  # Связи между моделями (служебное)
    "django.contrib.sessions",  # Хранение сессий пользователей
    "django.contrib.messages",  # Всплывающие сообщения (успех, ошибка)
    "django.contrib.staticfiles",  # Работа со статикой (CSS, JS, картинки)
    # Сторонние библиотеки
    "rest_framework",  # Django REST Framework — создание API
    "rest_framework_simplejwt",  # JWT-токены для безопасной авторизации через API
    "django_filters",  # Фильтрация данных в API (поиск, сортировка)
    "django_celery_beat",  # Планировщик задач Celery (периодические задачи)
    "drf_spectacular",  # Современная автодокументация API (OpenAPI 3.0)
    "corsheaders",  # Разрешает запросы к API с других доменов (нужно для фронтенда)
    # Приложения проекта
    "users",
    "documents",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),  # Имя нашей базы
        "USER": os.getenv("DB_USER"),  # Имя пользователя PostgreSQL
        "PASSWORD": os.getenv("DB_PASSWORD"),  # Пароль пользователя PostgreSQL
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
        # Нельзя использовать логин/email как часть пароля
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        # Минимальная длина пароля (по умолчанию 8 символов)
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
        # Запрещает популярные пароли (qwerty, 123456, password)
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
        # Запрещает пароли, состоящие только из цифр (12345678)
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

# Язык интерфейса (кнопки, надписи в админке)
LANGUAGE_CODE = "en-us"

# Часовой пояс
TIME_ZONE = "UTC"

# Интернационализация (переводы на другие языки)
USE_I18N = True

# Использовать часовые пояса (хранить время в UTC, показывать в локальном)
USE_TZ = True

# ТИП ПОЛЯ ПО УМОЛЧАНИЮ ДЛЯ ПЕРВИЧНЫХ КЛЮЧЕЙ
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ============================================
# СТАТИКА И МЕДИА
# ============================================

# URL для доступа к статике (CSS, JS админки)
STATIC_URL = "static/"

# URL для доступа к загруженным пользователями файлам
MEDIA_URL = "media/"

# === ПАПКИ ДЛЯ ХРАНЕНИЯ ФАЙЛОВ ===

# Папка, куда собираются все статические файлы из всех приложений
# Для продакшена: после деплоя нужно выполнить python manage.py collectstatic
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Папка, куда сохраняются загруженные пользователями файлы (документы, аватары)
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Дополнительные папки со статикой (только в разработке)
if DEBUG:
    STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]

# ============================================
# КАСТОМНАЯ МОДЕЛЬ ПОЛЬЗОВАТЕЛЯ
# ============================================

# Вместо стандартной модели User используется своя (users.User)
# Позволяет добавить свои поля (телефон, аватар, дата рождения)
AUTH_USER_MODEL = "users.User"


# ============================================
# DJANGO REST FRAMEWORK
# ============================================
REST_FRAMEWORK = {
    # Фильтрация по умолчанию (поиск и сортировка в API)
    "DEFAULT_FILTER_BACKENDS": ("django_filters.rest_framework.DjangoFilterBackend",),
    # Способ аутентификации через JWT-токены (вместо сессий/куки)
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    # Доступ по умолчанию: только авторизованные пользователи
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    # Генератор OpenAPI-схемы для автодокументации
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

# ============================================
# JWT (JSON Web Token)
# ============================================

SIMPLE_JWT = {
    # Access-токен: короткий (30 минут), передаётся с каждым запросом
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    # Refresh-токен: длинный (1 день), нужен чтобы получить новый access
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    # Тип токена в заголовке: Authorization: Bearer <токен>
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# Настройка отправки писем
EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_PORT = os.getenv("EMAIL_PORT")
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL")
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")

SERVER_EMAIL = EMAIL_HOST_USER
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


# ============================================
# НАСТРОЙКИ ДОКУМЕНТАЦИИ API (Swagger/OpenAPI)
# ============================================

SPECTACULAR_SETTINGS = {
    "TITLE": "Docs Processing API",  # Название API
    "DESCRIPTION": "API для сервиса управления загружаемыми документами.",  # Описание
    "VERSION": "1.0.0",  # Версия API
    "SERVE_INCLUDE_SCHEMA": False,  # Не показывать схему в ответах API
    "TAGS": [
        {"name": "documents", "description": "Управление документами"},
        {"name": "users", "description": "Пользователи"},
    ],
}

# ============================================
# REDIS (брокер для Celery)
# ============================================
REDIS_HOST = os.getenv("REDIS_HOST")
REDIS_PORT = os.getenv("REDIS_PORT")
REDIS_DB = os.getenv("REDIS_DB")

# ============================================
# CELERY
# ============================================
# Куда класть задачи (брокер)
CELERY_BROKER_URL = f"redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}"

# Где хранить результаты выполнения (бэкенд)
CELERY_RESULT_BACKEND = f"redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}"

# Часовой пояс для задач
CELERY_TIMEZONE = TIME_ZONE

# Логировать начало каждой задачи
CELERY_TASK_TRACK_STARTED = True

# Максимальное время выполнения задачи (30 минут)
CELERY_TASK_TIME_LIMIT = 30 * 60

# URL сайта для формирования ссылок в письмах
SITE_URL = os.getenv("SITE_URL")
# Email администратора для получения уведомлений о новых документах
ADMIN_EMAIL = os.getenv("ADMIN_EMAIL")

# Где хранить расписание (в базе данных)
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"

# ============================================
# РАСПИСАНИЕ ПЕРИОДИЧЕСКИХ ЗАДАЧ (CELERY BEAT)
# ============================================
CELERY_BEAT_SCHEDULE = {
    "check-overdue-documents-every-2-hours": {
        "task": "documents.tasks.check_overdue_documents",
        "schedule": crontab(minute="0", hour="*/2"),  # Каждые 2 часа
    },
}
